### ISSUE TITLE
Train.py not pickleable on Mac (spawn issue?)

### ISSUE THREAD

**Issue by FSLO** [claritychallenge/clarity#424]
Running train.py on Mac  results in pickling error, which doesn't happen on Linux. 
Seemingly it's related to the "lambda audio: audio" in the Cad2Task2_dataloader.
I've tested on two Macs and one Linux.

Traceback (most recent call last):
  File "/Users/missingotter/Documents/GitHub/SMC7-Cadenza/clarity/recipes/cad2/task2/ConvTasNet/train.py", line 161, in <module>
    main(arg_dic)
  File "/Users/missingotter/Documents/GitHub/SMC7-Cadenza/clarity/recipes/cad2/task2/ConvTasNet/train.py", line 131, in main
    trainer.fit(system)
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in _run
    results = self._run_stage()
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self._run_sanity_check()
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1052, in _run_sanity_check
    val_loop.run()
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 178, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 113, in run
    self.reset()
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 231, in reset
    iter(data_fetcher)  # creates the iterator inside the fetcher
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 104, in __iter__
    super().__iter__()
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 51, in __iter__
    self.iterator = iter(self.combined_loader)
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 351, in __iter__
    iter(iterator)
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 155, in __iter__
    self._load_current_iterator()
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 173, in _load_current_iterator
    self.iterators = [iter(self.iterables[self._iterator_idx])]
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 484, in __iter__
    return self._get_iterator()
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 415, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/anaconda3/envs/clarity/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1138, in __init__
    w.start()
  File "/opt/anaconda3/envs/clarity/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/anaconda3/envs/clarity/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/anaconda3/envs/clarity/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/opt/anaconda3/envs/clarity/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/anaconda3/envs/clarity/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/anaconda3/envs/clarity/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/anaconda3/envs/clarity/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x15a7dc820>: attribute lookup <lambda> on local.cad2task2_dataloader failed

**Comment by FSLO** [comment]
Seem
